"""Shared column definitions for CoCre8 onboarding outputs."""

RAW_STOCK_COLUMNS = [
    "ItemCode",
    "ItemName",
    "ItemsGroupCode",
    "GroupName",
    "WarehouseCode",
    "InStock",
    "MinStock",
    "OnOrder",
]

MINSTOCK3_FINAL_COLUMNS = [
    "PartNo",
    "ItemDescription",
    "GroupName",
    "WarehouseCode",
    "WarehouseName",
    "Location",
    "CustomerCode",
    "SPLMaster",
    "InStock",
    "MinimumStock",
    "GlobalInStock",
    "GlobalMin",
    "Shortage",
    "Ordered",
    "GlobalOrdered",
    "ItemKey",
    "MasterKey",
    "ReturnCode",
    "RepairCode",
    "ListPrice",
    "CreditPrice",
    "Used24",
    "Used25",
    "Used26",
    "CoCre8Cost",
    "RowSig",
    "RowKey",
]

CUSTOMER_COLUMNS = [
    "CustomerCode",
    "WarehouseCode",
    "GroupName",
    "WarehouseName",
    "Location",
]

FIELD_MAP_WORKBOOK = "CoCre8_PlanningV2_Field_Map.xlsx"

FIELD_MAP_SHEETS = [
    "Target Fields",
    "Source Evidence",
    "Unknowns",
    "Output Objects",
    "SAP Investigation Log",
]

TEMPLATE_OBJECT_DECISIONS = {
    "Models": {
        "status": "DEFERRED",
        "readiness": "Deferred post-MVP",
        "notes": "Chris feedback: important, but not for MVP.",
    },
    "RepairOrder": {
        "status": "OUT_OF_SCOPE",
        "readiness": "Out of CoCre8 scope",
        "notes": "Chris feedback: RepairOrder is not used by CoCre8.",
    },
    "ServiceOrder": {
        "status": "DEFERRED",
        "readiness": "Deferred post-MVP",
        "notes": "Chris feedback: this would be the HelpDesk ticket list, but without ticket close times it is not usable for MVP.",
    },
    "Yields": {
        "status": "DEFERRED",
        "readiness": "Deferred post-MVP",
        "notes": "Chris feedback: yield means expected uses or average years before breakdown; not for MVP.",
    },
    "Nodes": {
        "status": "DEFERRED",
        "readiness": "Deferred post-MVP",
        "notes": "Chris feedback: regional umbrella for warehouse/address hierarchy; not for MVP.",
    },
    "ActionGroups": {
        "status": "DEFERRED",
        "readiness": "Deferred post-MVP",
        "notes": "Chris feedback: technician/action group by region; not for MVP.",
    },
    "Employees": {
        "status": "DEFERRED",
        "readiness": "Deferred post-MVP",
        "notes": "User feedback: employees are not required for MVP.",
    },
    "WarehouseExclusions": {
        "status": "PASS",
        "readiness": "Ready",
        "notes": "Chris feedback: no warehouse exclusions to start with; empty upload is intentional.",
    },
}

CONFIRMED_OUTPUT_OBJECTS = {
    "spl_masters": [
        "part_id",
        "SPL MASTER",
        "Primary Part",
        "Description",
        "SPL Boot Stockable",
        "Boot Stockable",
        "Branch Stockable",
        "Product Class ID",
        "Product Type ID",
    ],
    "part_alternatives": ["part_id", "alt_part_id"],
    "parts": [
        "part_id",
        "description",
        "spl_master",
        "primary_part",
        "return_code",
        "repair_code",
        "list_price",
        "credit_price",
        "cocre8_unit_cost",
        "currency_id",
    ],
    "warehouses": [
        "warehouse_id",
        "descr",
        "location",
        "warehouse_type_id",
        "customer_code",
        "customer_name",
    ],
    "customers": ["company_id", "customer_name", "warehouse_id", "location"],
    "stock_detail": [
        "part_id",
        "warehouse_id",
        "qty",
        "allocated_qty",
        "in_bound_qty",
        "out_bound_qty",
        "minimum_stock",
        "maximum_stock",
        "inv_type_id",
    ],
    "usage": [
        "posting_date",
        "order_id",
        "part_id",
        "warehouse_id",
        "qty_used",
        "customer_id",
        "device_serial",
    ],
    "stock_flow": [
        "posting_date",
        "document",
        "document_type",
        "part_id",
        "warehouse_id",
        "quantity_signed",
    ],
}

PENDING_OUTPUT_OBJECTS = {
    "installed_base": ["part_id", "company_id", "serial_no", "address_id", "child_part_id", "qty"],
    "internal_inventory_movements": [
        "IMO",
        "created_at",
        "completion_dt",
        "LO_STATUS",
        "order_id",
        "fr_warehouse_id",
        "to_warehouse_id",
        "part_id",
        "qty",
    ],
    "work_order_information": [
        "creation_datetime",
        "cust_company_id",
        "open_date",
        "open_time",
        "order_id",
        "order_type_id",
        "site_company_id",
        "serial_no",
        "is_resolved",
    ],
    "technicians": ["person_id", "first_name", "middle_name", "last_name", "is_active", "phone_id"],
    "purchase_orders": [
        "poh_id",
        "creation_date",
        "approval_date",
        "po_status",
        "to_warehouse_id",
        "vendor_company_id",
        "part_id",
        "qty",
        "qty_received",
        "receive_date",
    ],
    "repair_orders": [
        "order_id",
        "repair_type",
        "creation_datetime",
        "part_id",
        "serial_no",
        "to_warehouse_id",
        "from_warehouse_id",
        "RA_status",
    ],
}
